/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Dec 6, 2012, 9:07:51 PM
 */
package simplex;

import java.awt.event.KeyEvent;

/**
 *
 * @author robert
 */
public class MainWindow extends java.awt.Frame {

	private NoiseCanvas canvas;

	/** Creates new form MainWindow */
	public MainWindow() {
		initComponents();

		canvas = new NoiseCanvas();
		add(canvas);

		canvas.setSize(800, 600);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
		System.exit(0);
    }//GEN-LAST:event_exitForm

private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
	if (evt.getKeyChar() == '+') {
		if (canvas.isUseSeed()) {
			canvas.setSeed(canvas.getSeed() + 1);
		}
		canvas.setUseSeed(true);
		canvas.repaint();
	} else if (evt.getKeyChar() == '-') {
		if (canvas.getSeed() > 0) {
			canvas.setSeed(canvas.getSeed() - 1);
		} else {
			canvas.setUseSeed(false);
		}
		canvas.repaint();
	}
}//GEN-LAST:event_formKeyTyped

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
